version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/cloud-deploy"
    schedule: { interval: "weekly" }
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
