FROM python:3.11-slim
WORKDIR /app

COPY cloud-deploy/requirements.ui.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /app/

EXPOSE 8501
ENV API_URL="http://localhost:8000"
CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
