name: CI
on:
  push:
  pull_request:
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 flake8==7.1.0 flake8-bugbear==24.4.26
      - name: Lint
        run: |
          black --check .
          flake8 .
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cloud-deploy/Dockerfile.api
          push: false
      - name: Build UI image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cloud-deploy/Dockerfile.ui
          push: false
